--  CREATE DATABASE AND SCHEMA IF NOT EXISTS
CREATE DATABASE DBT_DEMO;
CREATE SCHEMA DBT_DEMO.RAW;

-- SWITCH ROLE, DATABASE AND SCHEMA
USE ROLE ACCOUNTADMIN;
USE DATABASE DBT_DEMO;
USE SCHEMA DBT_DEMO.RAW;

-- CREATE RAW STAGE TABLES
-- Create RAW_CUSTOMERS
CREATE OR REPLACE TABLE DBT_DEMO.RAW.CUSTOMERS (
 CUSTOMER_ID INTEGER,
 CUSTOMER_NAME VARCHAR,
 STATUS VARCHAR,
 CREATED_AT TIMESTAMP
);

INSERT INTO DBT_DEMO.RAW.CUSTOMERS
 (CUSTOMER_ID, CUSTOMER_NAME, STATUS, CREATED_AT)
VALUES
 (101, 'Ravi', 'active', CURRENT_TIMESTAMP()),
 (102, 'Sara', 'active', CURRENT_TIMESTAMP()),
 (103, 'John', 'inactive', CURRENT_TIMESTAMP());

-- Create RAW_PRODUCTS
CREATE OR REPLACE TABLE DBT_DEMO.RAW.PRODUCTS (
 PRODUCT_ID INTEGER,
 PRODUCT_NAME VARCHAR,
 PRICE NUMBER(10,2),
 CREATED_AT TIMESTAMP
);

INSERT INTO DBT_DEMO.RAW.PRODUCTS
 (PRODUCT_ID, PRODUCT_NAME, PRICE, CREATED_AT)
VALUES
 (1, 'Laptop', 50000, CURRENT_TIMESTAMP()),
 (2, 'Mouse', 1000, CURRENT_TIMESTAMP()),
 (3, 'Keyboard', 2000, CURRENT_TIMESTAMP());

 -- Create RAW_ORDERS
CREATE OR REPLACE TABLE DBT_DEMO.RAW.ORDERS (
 ORDER_ID INTEGER,
 CUSTOMER_ID INTEGER,
 PRODUCT_ID INTEGER,
 ORDER_DATE DATE,
 ORDER_AMOUNT NUMBER(10,2),
 CREATED_AT TIMESTAMP
);

INSERT INTO DBT_DEMO.RAW.ORDERS
 (ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_DATE, ORDER_AMOUNT, CREATED_AT)
VALUES
 (1001, 101, 1, CURRENT_DATE(), 50000, CURRENT_TIMESTAMP()),
 (1002, 102, 2, CURRENT_DATE(), 1000, CURRENT_TIMESTAMP()),
 (1003, 999, 3, CURRENT_DATE(), 2000, CURRENT_TIMESTAMP());

-- Verify Snowflake
SELECT * FROM DBT_DEMO.RAW.CUSTOMERS;
SELECT * FROM DBT_DEMO.RAW.PRODUCTS;
SELECT * FROM DBT_DEMO.RAW.ORDERS;

